language: python

python:
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - python setup.py checkdocs  # check documentation (README.rst)
  - make -C docs html  # Build the documentation.

cases:
  - andes -p cases/ieee14 ieee14_syn.dm -r tds -v 10 --tf 0.1
  - andes -p cases/curent WECC_WIND50.dm -r tds -v 10 --tf 0.1
  - andes -p cases/npcc npcc48.raw --addfile npcc48.dyr -r tds -v 10 --rf 0.1
